{% set name = "outlines" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/outlines-{{ version }}.tar.gz
  sha256: 0233cb3ffae9cb6b01ad8d3c32b7d87e3f1cf7bdc7b28a0bc82cd3d277c09bca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - setuptools-rust
    - pip
  run:
    - python 
    - interegular
    - jinja2
    - lark
    - nest-asyncio
    - numpy
    - cloudpickle
    - diskcache
    - pydantic
    - referencing
    - jsonschema
    - requests
    - tqdm
    - typing_extensions
    - pycountry
    - airportsdata
    - pytorch
    - outlines-core ==0.1.26

test:
  imports:
    - outlines
  commands:
    - pip check
  requires:
    - python
    - pip
about:
  home: https://github.com/outlines-dev/outlines
  doc_url: https://outlines-dev.github.io/outlines
  summary: Probabilistic Generative Model Programming
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - maresb
    - pavelzw
