{% set name = "outlines" %}
{% set version = "1.3.0" %}
{% set pytest_ignore = [
  "--ignore=tests/backends/test_xgrammar.py",
  "--ignore=tests/models/test_dottxt.py",
  "--ignore=tests/models/test_lmstudio.py",
  "--ignore=tests/models/test_ollama.py",
  "--ignore=tests/types/test_custom_types.py",
  "--ignore=tests/backends/test_backends.py",
  "--ignore=tests/backends/test_outlines_core.py",
  "--ignore=tests/models/test_anthropic.py",
  "--ignore=tests/models/test_gemini.py",
  "--ignore=tests/models/test_llamacpp.py",
  "--ignore=tests/models/test_lmstudio_type_adapter.py",
  "--ignore=tests/models/test_mistral.py",
  "--ignore=tests/models/test_openai.py",
  "--ignore=tests/models/test_provider_exceptions.py",
  "--ignore=tests/models/test_llamacpp_type_adapter.py",
  "--ignore=tests/models/test_transformers_multimodal.py",
  "--ignore=tests/backends/test_llguidance.py",
  "--deselect=tests/models/test_transformers_multimodal_type_adapter.py::test_transformers_multimodal_type_adapter_format_output_type",
  "--deselect=tests/models/test_transformers_type_adapter.py::test_transformers_type_adapter_format_output_type",
  "--deselect=tests/test_generator.py::test_steerable_generator_init_valid_processor",
  "--deselect=tests/test_generator.py::test_steerable_generator_init_invalid_output_type",
  "--deselect=tests/test_generator.py::test_generator_init_multiple_output_type",
  "--deselect=tests/test_generator.py::test_generator_steerable_processor",
  "--deselect=tests/test_generator.py::test_generator_black_box_sync_processor",
  "--deselect=tests/test_generator.py::test_generator_black_box_async_processor",
  "--deselect=tests/test_exceptions.py::TestIsProviderException::test_sentinel_minus_one_is_not_provider",
]%}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/outlines-{{ version }}.tar.gz
  sha256: 2a515b8e5e446660ea1f7a0ecb7f08d9e646cd3b1cdafab228574acfeabe6f86

build:
  skip: true  # [py<310 or py>313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - jinja2
    - cloudpickle
    - diskcache
    - pydantic >=2.0
    - jsonschema
    - typing_extensions
    - outlines-core ==0.2.14
    - pillow
    - genson
    - jsonpath-ng

test:
  source_files:
    - tests/
  imports:
    - outlines
  commands:
    - pip check
    - pytest -vvv tests {{pytest_ignore | join(" ")}}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - transformers
    - pytorch
    - llama-cpp-python
    - anthropic
    - google-genai
    - openai
    - mistralai
    - llguidance
    - datasets

about:
  home: https://dottxt-ai.github.io/outlines/
  summary: Outlines guarantees structured outputs during generation
  description: |
    LLMs are powerful but their outputs are unpredictable. Most solutions attempt to fix bad
    outputs after generation using parsing, regex, or fragile code that breaks easily.

    Outlines guarantees structured outputs during generation — directly from any LLM.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://dottxt-ai.github.io/outlines/
  dev_url: https://github.com/dottxt-ai/outlines

extra:
  recipe-maintainers:
    - maresb
    - pavelzw
